In [4]:
#importing libraries
import numpy as np
import pandas as pd

In [5]:
#loading dataset
data = pd.read_csv('tagged_data.csv')

In [6]:
data.head()

word   tag
0   American  MISC
1     League  MISC
2  Cleveland   ORG
3    DETROIT   ORG
4  BALTIMORE   ORG

In [7]:
#featurising the inputs into non-string values
def get_unique_word(df):
    words = list(set(df.word))
    unique = dict()
    for i in range(len(words)):
        unique[words[i]] = i
    return unique

def get_unique_tag(df):
    words = list(set(df.tag))
    unique = dict()
    for i in range(len(words)):
        unique[words[i]] = i
    return unique

u = get_unique_word(data)
t = get_unique_tag(data)

# print(u)
# print(t)

# labels, _ = pd.factorize(data.word)
u

{'Gheorghe': 0,
 'Nepal': 1,
 'Kate': 4,
 'Ulker': 4481,
 'Jingna': 4482,
 'Mind': 4483,
 'Raoux': 4484,
 'Ghibellines': 6,
 'Refugees': 5,
 'Loine': 7836,
 'Codos': 4485,
 'STOCKHOLM': 7,
 'PARIS': 2,
 'Bridgend': 6717,
 'CNB': 10,
 'Leonardo': 9,
 'Winston': 4488,
 'JERSEY': 4489,
 'Mistr': 11,
 'SIMEX': 4491,
 'GROBBELAAR': 12,
 'Dariusz': 13,
 'Carretero': 719,
 'Symcox': 14,
 'Korean': 6549,
 'Scholl': 15,
 'Staff': 16,
 'BUSINESS': 4492,
 'Vitoux': 17,
 'Rating': 18,
 'Tigers': 19,
 'Bravo': 20,
 'Panathinaikos': 21,
 'Ameritech': 4494,
 'Caminero': 4495,
 'Bissell': 23,
 'Reef': 24,
 'Hueite': 4496,
 'Berne': 25,
 'Ohrel': 4499,
 'Alain': 26,
 'Karol': 6552,
 'Green': 2023,
 'Mae': 27,
 'Shield': 4501,
 'Nannan': 28,
 'Ales': 29,
 'et': 4502,
 'Baltimore': 30,
 'Ensemble': 31,
 'Jill': 32,
 'Barbara': 4504,
 'MIDEAST': 4505,
 'Liberian': 33,
 'Crawford': 6460,
 'Limited': 4506,
 'Jomhuri': 4507,
 'GATTING': 7425,
 'Suzuki': 4508,
 'Dopita': 4509,
 'Lebanese': 4510,
 'Tamils': 45

In [8]:
X = np.array([u[word] for word in data.word]).reshape(-1, 1)
y = np.array([t[tag] for tag in data.tag]).reshape(-1, 1)

In [9]:
# from sklearn.naive_bayes import GaussianNB
# clf = GaussianNB()

from sklearn import tree
clf = tree.DecisionTreeClassifier()

In [10]:
X

array([[1329],
       [5257],
       [7243],
       ...,
       [1731],
       [1264],
       [7547]])

In [11]:
y

array([[4],
       [4],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
#training
clf.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [14]:
X_test

array([[8016],
       [3516],
       [4687],
       ...,
       [2957],
       [4210],
       [7664]])

In [15]:
y_test

array([[3],
       [0],
       [0],
       ...,
       [3],
       [1],
       [0]])

In [16]:
y_pred = clf.predict(X_test)

In [17]:
print(y_test)
print(y_pred)

[[3]
 [0]
 [0]
 ...
 [3]
 [1]
 [0]]
[3 0 0 ... 3 1 0]


In [18]:
#performance
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

0.9194768217812973

In [19]:
# I used the decision tree classifier because the Gaussian Naive Bayes gave merely a 33% accuracy.
# THANK YOU.